### ISSUE TITLE
Help tired developers by making the URL swap step to use Blocks super obvious

### ISSUE THREAD

**Issue by JustinGOSSES** [githubnext/blocks#37]
#### Problem:
I spent a while looking around trying to figure out how to use blocks on repos that were not the demo repo. 

#### Why I got confused:
The words that were supposed to tell me what to do were
`We've created an app at: [blocks.githubnext.com](https://blocks.githubnext.com/) that lets you view your files and repositories with different Blocks.`

Unfortunately, I had attempted to try out Blocks when I had some time to play around with it, which was late at night after my brain had stopped working. 

I misinterpreted the words above to mean "_here is the URL to the demo_" instead of "_swap out that base URL for the normal github.com base url that you're used to in any repository_". This caused me to keep looking for instructions elsewhere.

### Suggestion:
_Make it more explicit what steps to take to try Blocks on your own repository by adding another sentence._ 

At the end of this sentence:
`We've created an app at: [blocks.githubnext.com](https://blocks.githubnext.com/) that lets you view your files and repositories with different Blocks.`
insert the following:
` To try out blocks, swap out https://blocks.githubnext.com/ for https://github.com/ in the URL to a repo's README.`

**Comment by mheap** [comment]
I had the same issue and ended up putting https://github.com/mheap/chrome-extension-open-in-blocks together

**Comment by jaked** [comment]
thanks for the report! It looks like the README was substantially rewritten and now explains this in the second paragraph:

![CleanShot 2022-12-14 at 12 14 02](https://user-images.githubusercontent.com/56439/207704612-9e047d6a-e85c-4132-b8a7-1bff6ebfa31b.png)

(see https://blocks.githubnext.com/githubnext/blocks/blob/main/README.md)

I'm going to close the issue.
