### ISSUE TITLE
Sandbox-Block: Block not found

### ISSUE THREAD

**Issue by muescha** [githubnext/blocks#54]
### what i do:

i open this link: 
- https://blocks.githubnext.com/githubnext/blocks/blob/main/examples/lodash%20docs/index.md?fileRef=&blockKey=githubnext__blocks-examples__markdown-block

### what i see

- error message: `Block not found`

### what i expect

- to see the example as block

### screenshot

![Bildschirm­foto 2023-03-03 um 04 09 11](https://user-images.githubusercontent.com/184316/222621995-ebd3e6cf-5d78-4301-b9ce-016e1c797870.png)

**Comment by jaked** [comment]
thanks for the report, this was fixed in ff9f3db5b7bbd273b91b9318f951ae1f77c86624
